// <auto-generated />
namespace Supeng.Examination.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renametestpaperquestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renametestpaperquestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201607030059587_rename-testpaperquestion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
